import Header from "./components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";

import {Providers} from "../redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Store App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
